// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MythMaker.Data;

#nullable disable

namespace MythMaker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241126213401_addForeignKeyForCategoryProductRelation")]
    partial class addForeignKeyForCategoryProductRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MythMaker.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            ImagePath = "images/category-1.jpg",
                            Name = "Dragons"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            ImagePath = "images/category-2.jpg",
                            Name = "Unicorns"
                        });
                });

            modelBuilder.Entity("MythMaker.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Meet Luna, the Moonlit Watcher. With scales that shift in shades of deep sapphire blue flecked with silver, Luna looks as if she’s bathed in starlight. Her emerald green eyes are fierce and intelligent, and her slender, curving horns add to her elegance. She watches over the world from rocky outcrops under a foggy, dawn-lit sky, surrounded by mystical wisps of smoke. Luna is calm, reflective, and perfect for those who feel drawn to moonlit mysteries and dreamlike landscapes.",
                            DisplayOrder = 1,
                            ImagePath = "images/products/dragon-1",
                            Name = "Luna, the Moonlit Watcher",
                            Price = 1.75
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Meet Sylvandar, the Forest Guardian. With shimmering emerald green and teal scales flecked with gold, Sylvandar looks like a living piece of the forest itself. His amber eyes hold a wise yet powerful gaze, and his twisted, branch-like horns tell of ancient times. Sylvandar lives in a dense, misty forest, where sunlight filters softly through the trees at dusk, illuminating his presence. He’s a gentle giant who loves peace and balance, perfect for those who feel most at home among the trees and whispering leaves.",
                            DisplayOrder = 1,
                            ImagePath = "images/products/dragon-2",
                            Name = "Sylvandar, the Forest Guardian",
                            Price = 1.8
                        });
                });

            modelBuilder.Entity("MythMaker.Models.Product", b =>
                {
                    b.HasOne("MythMaker.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
